name: Go

on:
  push:
    branches: [ master ]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]

jobs:

  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # go: ['1.11', '1.12', '1.13', '1.14']
        go: ['1.16']

    #env:
    #  COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - id: go
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          for GOOS in $(go tool dist list|awk -F'/' '{print $1}'|sort -u); do
            echo -e "\n\nTESTING FOR $GOOS ...\n"
            go test -v -race -coverprofile=profile.cov ./...
          done

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          parallel: true

  # notifies coveralls that all test jobs are finished
  finish:
    name: Finish
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true








